name = "job-collector"
main = "src/workers/job-collector.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Trigger the worker twice daily
[triggers]
crons = ["0 0 * * *", "0 12 * * *"]

# Environment variables
[vars]
API_SECRET = "your-api-secret-here"
NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url-here"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key-here"

# Supabase credentials
SUPABASE_URL = "your-supabase-url-here"
SUPABASE_SERVICE_KEY = "your-supabase-service-key-here" 