name = "job-changes-cleanup"
main = "src/workers/job-changes-cleanup.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Trigger the worker once daily at 3:00 AM UTC
[triggers]
crons = ["0 3 * * *"]

# Environment variables
[vars]
API_SECRET = "gtttbFRmzN1pB7DdN6rnKOEqVhXAj8jtbEKJlP2V1k"
NEXT_PUBLIC_SUPABASE_URL = "https://cpgwkmqyffzhuqnfwahq.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZ3drbXF5ZmZ6aHVxbmZ3YWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMTM3OTUsImV4cCI6MjA1Njc4OTc5NX0.ClLCaCiNMokfgBpLy4n23ic-M19SkCDXsRF54YwUcb4"

# Supabase credentials
SUPABASE_URL = "https://cpgwkmqyffzhuqnfwahq.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZ3drbXF5ZmZ6aHVxbmZ3YWhxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTIxMzc5NSwiZXhwIjoyMDU2Nzg5Nzk1fQ.USgZZKTYMxQIM-s-OsZfWQ5o6t_auaVD95aQCOjXpr4" 