name = "job-collector"
main = "src/workers/job-collector.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Trigger the worker twice daily
[triggers]
crons = ["0 0 * * *", "0 12 * * *"]

# Environment variables
[vars]
API_SECRET = "gtttbFRmzN1pB7DdN6rnKOEqVhXAj8jtbEKJlP2V1k"
NEXT_PUBLIC_SUPABASE_URL = "https://cpgwkmqyffzhuqnfwahq.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZ3drbXF5ZmZ6aHVxbmZ3YWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3OTQxOTksImV4cCI6MjA1NjM3MDE5OX0.nfIBDdiLn1SlFpAK5Hbkgtd04wnDJAxYTgVCWImJ-rE"

# Supabase credentials
SUPABASE_URL = "https://cpgwkmqyffzhuqnfwahq.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZ3drbXF5ZmZ6aHVxbmZ3YWhxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDc5NDE5OSwiZXhwIjoyMDU2MzcwMTk5fQ.ejuiz7HJxbyYVCXRbyIfHNp46ZHC-pOXdX89GnT9NYE"